### PR TITLE
raw output in file

### LINKED ISSUE #6: Allow to dump raw results into a file.
Currently all output goes into `stdout`. This way it makes impossible to get raw results without additional output when run with stack. As `stack bench ..` will write it's own output, and `stack bench --silent` hides all output including output of the hyperion.

Proposal:

Change meaning of the `--raw` option and make it `--raw=file.json` in case if it's set -- all output should go into the `file.json` instead. And stdout output should be same as without `--raw` option.

### PR DESCRIPTION
**Pull request by gamazeps**
Attempts to fix #6, based on the work done on #12 

The UX is the following:
- If the user provided no `--output` flag and provided the `--raw` flag, both the raw and regular outputs are dumped to stdout.
- If the user provided both `--output=PATH` and `--raw` flags, the regular output will be dumped to `PATH/executableName.benchName.json` and the raw output will be dumped to `PATH/executableName.benchname.raw.json`

### CODE REVIEW

**Comment by gamazeps** [comment]
Rebased #13 on top of #12 so that tests pass

**Comment by mboes** [comment]
Could we spec out the UX we want in the Asana ticket first? I disagree with two things:

* if the user specified an `--output` path, what's the value of creating an additional *.raw file? Why not put everything exactly where the user told us to put things?
* By both "raw and regular output", do you mean pretty printed human output + JSON output? If so, the user won't be interested in JSON output in that case, or she is, it will be garbled by the regular output so not easily pipable.

**Comment by gamazeps** [comment]
@m, @qnikst mentionned that the user could want both the json with the raw output and without the raw output, thus the need for two files.

This also answers your second question (by regular I mean json without raw measurement).

**Comment by qnikst** [comment]
That time we didn't have pretty printed output. I think that pretty printer (not nessecary goes to any file) and file with all results will suit all use case scenarios.

**Comment by gamazeps** [comment]
Closing then

**Pull request closed without merging**
